# config.yaml
# === Subject info ===
subinfo_fields:
  - name: subject_id
    type: int
    constraints:
      min: 101
      max: 999
      digits: 3

  - name: subname    
    type: string

  - name: age 
    type: int
    constraints:
      min: 5
      max: 60

  - name: gender
    type: choice
    choices: [Male, Female]

subinfo_mapping:
    subject_id: "被试号"
    subname: "被试姓名(拼音)"
    age: "年龄"
    gender: "性别"
    Male: "男"
    Female: "女"
    registration_failed: "注册失败。"
    registration_successful: "注册成功！"
    invalid_input: "字段 {field} 输入无效"


# === Window settings ===
window:
  size: [1920, 1080]
  units: deg
  screen: 1
  bg_color: black
  fullscreen: True
  monitor_width_cm: 60
  monitor_distance_cm: 72

# === Task-level settings ===
task:
  task_name: "eeg_movie_present"
  language: "Chinese"
  voice_name: "zh-CN-YunyangNeural"
  total_blocks: 1
  total_trials: 1
  trial_per_block: 1
  conditions: [movie]
  key_list: []
  seed_mode: "same_across_sub"


# === Stimuli (for MID task) ===
stimuli:
  fixation:
    type: text
    text: "+"
    color: white

  movie:
    type: movie
    filename: "./assets/presentch.mp4"
    size: [22.1, 12.4]
    units: deg
  
  
  instruction_text:
    type: textbox
    text: |
      【观影任务说明】

      接下来您将观看一段视频

      请尽量保持放松和安静，注视屏幕中央
      观看过程中请避免身体移动和频繁眨眼
      只需自然观看并保持专注即可
      如果准备好了
      请按【空格键】开始任务
    color: white
    pos: [0, 0] 
    font: SimHei
    alignment: center
    letterHeight: 0.78
    units: deg
    size: [20, 5]
  
  good_bye:
    type: textbox
    text: |
      任务结束
      
      感谢您的参与
      请按【空格键】退出
    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78
    units: deg
    size: [20, 5]
    
timing:
  movie_duration: 204

triggers:
  exp_onset: 98
  exp_end: 99

  block_onset: 100
  block_end: 101

  movie_onset: 1
  movie_offset: 2


